### ISSUE TITLE
Unable to add logging with Azure app insights or new relic 

### ISSUE THREAD

**Issue by VBPanchal** [apollographql/router#2434] opened 2023-01-19 14:11 UTC
We are using Azure app insignts and new relic for the logging performace evalution, in other our previous federation  gateway we are using this. 

As we have already options for the jaeger and oltp, we can also provide azure appinsights and new relic for logging purpose

Please provide idea to integrate with custom plugin or other resources

**Comment by Geal** [comment] 2023-01-19 15:44
closed as duplicate of #2433

**Closed by Geal** 2023-01-19 15:44 UTC
Labels: triage, raised by user
