### ISSUE TITLE
Update opentelemetry_datadog and expose span name mapping

### ISSUE THREAD

**Issue by dragonbear-os** [apollographql/router#2228] opened 2022-12-07 15:16 UTC
The default mapping of span name for datadog leaves much to be desired.

For most datadog integrations something meaningful is set for the name of the span:

<img width="333" alt="Screen Shot 2022-12-07 at 10 09 53 AM" src="https://user-images.githubusercontent.com/102992960/206215767-59a6877c-8e8f-4985-b63c-9bc6fce9549d.png">

Because opentelemetry requires the span name to be a static str, we get things like:

<img width="293" alt="Screen Shot 2022-12-07 at 10 10 43 AM" src="https://user-images.githubusercontent.com/102992960/206215975-4a61f429-9b6e-467a-bc2b-69556a12906f.png">

If you upgrade the datadog integration to 0.6.0 there is an exposed set of mappings that let this be customized:

https://docs.rs/opentelemetry-datadog/0.6.0/opentelemetry_datadog/struct.DatadogPipelineBuilder.html#method.with_name_mapping

It would be great to add something to the config that is like an alternate name based on an attribute on the span and then call that name mapping function to pull that attribute off the span.

I can think of some other ways to do this but they are all require us to not use a lot of the builtin tracing setup and reimplement a bunch of things.

What I would really like is for the Executable to expose some configuration directly that gives hooks for this kind of thing so that a custom binary can do something like:

```
apollo_router::ExecutableBuilder()
  .with_datadog_config(|config| {
    config.with_name_mapping(|span, _| { ... })
  })
  .build()?
  .main()
```

I understand that figuring out that API and even if you want to support something like that would be a lot. So adding a simple name attribute lookup would be really helpful.

**Comment by bnjjj** [comment] 2022-12-07 16:38
We currently have a PR to upgrade to otel 0.18 #1970 but it's not so simple because some crates containing fixes are not yet released on crate.io. We are currently considering our different options to do a release including these fixes even if it's not already published on crates.io (TLDR you can't publish on crates.io with a git dependency). 

But I will try to reproduce your example because I'm not sure to understand correctly. If you had an example of what you currently have vs what you would like to have that would be easier for me I guess

**Comment by Meemaw** [comment] 2022-12-14 16:03
@bnjjj it seems that otel 0.18 upgrade was merged. To clarify the ask here -- we would like to create a span which we can move with a dynamic value.

Some pseudocore for posterity:

```python
span = create_span(name=query_name)
```

**Comment by bnjjj** [comment] 2022-12-14 16:07
Yes in the latest release you have the last release of opentelemetry and also the opentelemetry datadog. Is it enough for your needs or do you need something on our side ?

**Closed** 2023-03-17 08:25 UTC
Labels: component/insights, triage, raised by user
