### ISSUE TITLE
v0.11.0: plugin initialization errors: insta snapshot failures for traced_basic_composition and traced_basic_request

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1407] opened 2022-07-15 14:09 UTC
After fixing the [plugin handler initialisation issue](https://github.com/apollographql/router/issues/1400), we were planning to cut a new release. However, after the fix was integrated we noticed intermittent errors in two of the snapshot generating tests:

integration_tests__traced_basic_composition and integration_tests__traced_basic_request

These tests use `insta` snapshotting to compare the spans generated when the tests are run. The issue is that both tests generate different results when executed (without change to environment or code) which makes our CI tests fail. This only appears to affect MacOS testing.

At this time, we aren't sure of the issue is a real issue in our code or an issue in the testing code which generates snapshots as input to `insta`.

We don't want to cut a new release until this is resolved and since we know that 0.11.0 is broken, we recommend staying on 0.10.0 until this issue is addressed.

**Comment by o0Ignition0o** [comment] 2022-07-18 11:19
#1040 is a workaround until we figure out exactly what is failing and why. We believe the tracing switch from `lazy_static` to `once_cell` may be the cause. I'll check

**Comment by abernix** [comment] 2022-08-31 07:41
@o0Ignition0o any updates on this?

**Comment by o0Ignition0o** [comment] 2022-09-12 08:24
Closing since telemetry has evolved a fair bit since, and we don't need those tests to assert against snapshots anymore.

**Closed by o0Ignition0o** 2022-09-12 08:24 UTC

**Comment by bnjjj** [comment] 2022-11-21 13:57
Will be updated in this PR https://github.com/apollographql/router/pull/2040/files#diff-aca654efc6c22bebf4bd167370ab3bf380f3e086befe3d7c6761a8f7eb59d89cL182
