### ISSUE TITLE
If the coprocessor is unreachable the Router does not log any errors that it cannot connect

### ISSUE THREAD

**Issue by clocked0ne** [apollographql/router#4331] opened 2023-12-05 12:32 UTC
**Describe the bug**
When a coprocessor is configured for the router - in this example only for subgraph requests - if the coprocessor is not running/otherwise cannot be reached, the Router logs and responds with a misleading error message that "client requires absolute-form URIs" and not a response that the Router cannot connect to the coprocessor.

**To Reproduce**
1. Run a router with the following configuration for only the subgraph stage:

```yaml
coprocessor:
  url: http://127.0.0.1:8081
  subgraph:
    all:
      request:
        headers: true
        body: true
        context: false
        uri: true
        method: true
        service_name: false
```

2. Send a request containing a query that would require a subgraph resolver
3. Response contains `SUBREQUEST_HTTP_ERROR` with reason "client requires absolute-form URIs"

**Expected behavior**
The Router logs should indicate that the coprocessor is unreachable even if the actual request response does not.

Maybe there should be an option to configure an initial or regular coprocessor 'healthcheck' as well?

**Output**
Router log output:

```bash
2023-12-05T12:07:13.348821Z DEBUG external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=<subgraph_name>,} execution{graphql.operation.type=query,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  co-processor returned co_processor_result=Err(hyper::Error(User(AbsoluteUriRequired)))
2023-12-05T12:07:13.351462Z ERROR external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=<subgraph_name>,} execution{graphql.operation.type=query,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  external extensibility: subgraph request stage error: client requires absolute-form URIs
2023-12-05T12:07:13.357015Z ERROR execution{graphql.operation.type=query,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  Fetch error: HTTP fetch failed from '<subgraph_name>': client requires absolute-form URIs
```

Request response:
```json
{
    "data": null,
    "errors": [
        {
            "message": "HTTP fetch failed from '<subgraph_name>': client requires absolute-form URIs",
            "path": [],
            "extensions": {
                "code": "SUBREQUEST_HTTP_ERROR",
                "service": "<subgraph_name>",
                "reason": "client requires absolute-form URIs"
            }
        }
    ]
}
```

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6
 - Router version 1.34.0

**Additional context**
When the example coprocessor I had was running it could easily be reached via Postman, the response remained the same. I believe my particular issue is with the Docker configuration but the vague error message here meant I wasted a lot of time trying to work out if the running coprocessor was even responding to the Router or not.

**Comment by nicholascioli** [comment] 2024-01-25 17:23
Hello, I'm having issues reproducing your exact error. I've tried running the router with the coprocessor config you have provided under different error conditions and different router versions (1.34.0 and 1.38.0), with the results of those tests listed below. All tests were made to the starstuff example supergraph with the following GraphQL query

```graphql
query ExampleQuery {
  me {
    id
  }
}
```

Let me know if there is something else I can test to reproduce.

### Router with the coprocessor not running
#### v1.34.0
```shell
# Shell output
2024-01-25T17:02:47.793586Z  DEBUG [trace_id=85bde1d7ab21ca4fb3de669f38512bd7] co-processor returned co_processor_result=Err(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))
2024-01-25T17:02:47.793623Z  ERROR [trace_id=85bde1d7ab21ca4fb3de669f38512bd7] external extensibility: subgraph request stage error: error trying to connect: tcp connect error: Connection refused (os error 61)
2024-01-25T17:02:47.793851Z  ERROR [trace_id=85bde1d7ab21ca4fb3de669f38512bd7] Fetch error: HTTP fetch failed from 'accounts': error trying to connect: tcp connect error: Connection refused (os error 61)
```

```jsonc
// Router resposne
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'accounts': error trying to connect: tcp connect error: Connection refused (os error 61)",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "accounts",
        "reason": "error trying to connect: tcp connect error: Connection refused (os error 61)"
      }
    }
  ]
}
```

#### v1.38.0
```shell
# Shell output
2024-01-25T17:18:50.504698Z DEBUG external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=accounts,} external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  co-processor returned co_processor_result=Err(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))
2024-01-25T17:18:50.504751Z ERROR external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=accounts,} external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  external extensibility: subgraph request stage error: error trying to connect: tcp connect error: Connection refused (os error 61)
2024-01-25T17:18:50.505003Z ERROR external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  Fetch error: HTTP fetch failed from 'accounts': error trying to connect: tcp connect error: Connection refused (os error 61)
```

```jsonc
// Router resposne
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'accounts': error trying to connect: tcp connect error: Connection refused (os error 61)",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "accounts",
        "reason": "error trying to connect: tcp connect error: Connection refused (os error 61)"
      }
    }
  ]
}
```

### Router with the coprocessor returning invalid data with valid status code
#### v1.34.0
```shell
# Shell output
2024-01-25T17:11:23.452365Z  DEBUG [trace_id=292faacb349a63745cd9b2db32f0c0b3] co-processor returned co_processor_result=Err(Error("expected value", line: 1, column: 1))
2024-01-25T17:11:23.452421Z  ERROR [trace_id=292faacb349a63745cd9b2db32f0c0b3] external extensibility: subgraph request stage error: expected value at line 1 column 1
2024-01-25T17:11:23.452731Z  ERROR [trace_id=292faacb349a63745cd9b2db32f0c0b3] Fetch error: HTTP fetch failed from 'accounts': expected value at line 1 column 1
```

```jsonc
// Router resposne
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'accounts': expected value at line 1 column 1",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "accounts",
        "reason": "expected value at line 1 column 1"
      }
    }
  ]
}
```

#### v1.38.0
```shell
# Shell output
2024-01-25T17:19:46.116556Z DEBUG external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=accounts,} external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  co-processor returned co_processor_result=Err(Error("expected value", line: 1, column: 1))
2024-01-25T17:19:46.116667Z ERROR external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=accounts,} external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  external extensibility: subgraph request stage error: expected value at line 1 column 1
```

```jsonc
// Router resposne
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'accounts': expected value at line 1 column 1",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "accounts",
        "reason": "expected value at line 1 column 1"
      }
    }
  ]
}
```

### Router with the [coprocessor](https://github.com/apollosolutions/summit-coprocessors-workshop/tree/main/coprocessor) running valid data with invalid status code
#### v1.34.0
```shell
# Shell output
2024-01-25T17:13:26.429845Z  DEBUG [trace_id=8b1ac8590f99b3e57fc466d9cba91670] co-processor returned co_processor_result=Ok(Externalizable { version: 1, stage: "SubgraphRequest", control: Some(Continue), id: Some("5b2e894d-19db-4eb9-b48c-53c58ad920ef"), headers: Some({}), body: Some(Object {"query": String("query ExampleQuery__accounts__0{me{id}}"), "operationName": String("ExampleQuery__accounts__0")}), context: None, sdl: None, uri: Some("https://accounts.demo.starstuff.dev/"), method: Some("POST"), path: None, service_name: None, status_code: None, has_next: None })
```

```jsonc
// Router resposne
{
  "data": {
    "me": {
      "id": "1"
    }
  }
}
```

#### v1.38.0
```shell
# Shell output
2024-01-25T17:21:10.910414Z DEBUG external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=accounts,} external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  co-processor returned co_processor_result=Ok(Externalizable { version: 1, stage: "SubgraphRequest", control: Some(Continue), id: Some("b3589add-5bcb-4706-9cf5-a82330aab0d2"), headers: Some({"apollo-federation-include-trace": ["ftv1"]}), body: Some(Object {"query": String("query ExampleQuery__accounts__0{me{id}}"), "operationName": String("ExampleQuery__accounts__0")}), context: None, sdl: None, uri: Some("https://accounts.demo.starstuff.dev/"), method: Some("POST"), path: None, service_name: None, status_code: None, has_next: None, query_plan: None })
```

```jsonc
// Router resposne
{
  "data": {
    "me": {
      "id": "1"
    }
  }
}
```

### Router with the [coprocessor](https://github.com/apollosolutions/summit-coprocessors-workshop/tree/main/coprocessor) timing out
#### v1.34.0
```shell
# Shell output
2024-01-25T17:17:04.482975Z  DEBUG [trace_id=fe31949c0c1302bba456cce6410980bc] co-processor returned co_processor_result=Err(Elapsed(()))
2024-01-25T17:17:04.483180Z  ERROR [trace_id=fe31949c0c1302bba456cce6410980bc] external extensibility: subgraph request stage error: request timed out
2024-01-25T17:17:04.484461Z  ERROR [trace_id=fe31949c0c1302bba456cce6410980bc] Fetch error: HTTP fetch failed from 'accounts': request timed out
```

```jsonc
// Router resposne
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'accounts': request timed out",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "accounts",
        "reason": "request timed out"
      }
    }
  ]
}
```

#### v1.38.0
```shell
# Shell output
2024-01-25T17:22:16.007502Z DEBUG external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=accounts,} external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  co-processor returned co_processor_result=Err(Elapsed(()))
2024-01-25T17:22:16.007667Z ERROR external_plugin{external service=subgraph :: Request,} fetch{apollo.subgraph.name=accounts,} external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  external extensibility: subgraph request stage error: request timed out
2024-01-25T17:22:16.011958Z ERROR external_plugin{external service=execution :: Request,} external_plugin{external service=supergraph :: Request,} external_plugin{external service=router :: Request,} request{http.method=POST,http.request.method=POST,http.route=/,http.flavor=HTTP/1.1,}  Fetch error: HTTP fetch failed from 'accounts': request timed out
```

```jsonc
// Router resposne
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'accounts': request timed out",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "accounts",
        "reason": "request timed out"
      }
    }
  ]
}
```

**Comment by abernix** [comment] 2024-02-12 10:52
We're happy to reinvestigate if you're still experiencing this problem, but will close this issue for now.  Thanks!

**Closed by abernix** 2024-02-12 10:52 UTC
Labels: raised by user

**Comment by pulkitjo** [comment] 2025-07-02 16:27
@abernix I have one question. is there any validation of co-processor URL during router deployment ? 
we recently had an issue where a faulty co-processor URL was added in router.yaml. this didn't cause any failure during deployment  but after the deployment, the router started to fail all the incoming requests because coprocessor was not reachable.

> "body": "external extensibility: subgraph request stage error: client requires absolute-form URIs",
>   "severity": "error",


Do let me know if you need more details .
