### ISSUE TITLE
Add topologySpreadConstraints to Helm chart

### ISSUE THREAD

**Issue by sylr** [apollographql/router#3903] opened 2023-09-26 09:37 UTC
**Describe the solution you'd like**

Add possibility to define `topologySpreadConstraints` in the helm chart.

**Describe alternatives you've considered**

None.

**Additional context**

https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Comment by smyrick** [comment] 2023-09-26 18:03
Duplicate of https://github.com/apollographql/router/issues/3891

**Closed** 2023-09-26 18:09 UTC
Labels: raised by user
