### ISSUE TITLE
deno: couldn't deserialize response : Error("missing field `extensions`", ...

### ISSUE THREAD

**Issue by Mithras** [apollographql/router#1519] opened 2022-08-16 18:04 UTC
**Describe the bug**
I don't understand this bug. What I'm trying to do is
```gql
query TestQuery($ids: [Long!], $regionId: Long!) {
  common {
    services(ids: $ids){
      name
      buildoutDurations(regionIds: [$regionId]) {
        durationInDays
        region {
          demandId # subgraph A
          id # subgraph B
          name # fails because of this field. The field is @shared by both subgraphs
        }
      }
    }
  }
}
```
The query fails with
```
{
  "errors": [
    {
      "message": "value retrieval failed: router bridge error: the deno runtime raised an error: `request: couldn't receive response couldn't deserialize payload `id: 6fb84bac-14c9-4efe-90c4-f105cf7eda4c`: `deno: couldn't deserialize response : `Error(\"missing field `extensions`\", line: 0, column: 0)``.`",
      "locations": [],
      "path": null
    }
  ]
}
```
Now it gets more weird. If I manually alter supergraph
```gql
  # this definition of name doesn't work
  name: String @join__field(graph: A, type: "String") @join__field(graph: B, type: "String")

  # this definition of name works
  name: String @join__field(graph: A, type: "String")

  # this definition of name works
  name: String @join__field(graph: B, type: "String")
```
so the error only repos when the field is shared. When it's not shared it resolves fine by either of subgraphs.
And even more weird, if I reduce nesting like such
```gql
query TestQuery {
  # subgraph A
  common { 
    region(regionId: 4) {
      id
      demandId
      name
    }
  }
  # subgraph B
  azure {
    regions {
      id
      demandId
      name
    }
  }
}
```
The same exact region fields resolve fine from both subgraphs regardless of which of is the entry subgraph if that makes sense.

**To Reproduce**
I can't come up with a simple repo steps.

**Expected behavior**
It works.

**Output**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 0.15.1

**Additional context**
Looking at the telemetry, it seems that the router fails before it does any subgraph requests:
![image](https://user-images.githubusercontent.com/2098029/184948370-af1899ff-1bc5-4231-b13f-f8429351bc79.png)
![image](https://user-images.githubusercontent.com/2098029/184948142-1e21932e-6291-407e-857e-02b7003c9553.png)

**Comment by jmauerhan** [comment] 2022-08-18 19:31
I'm getting the same error with my federated graph in Apollo Router, but querying other services for the same entity works, we only get the error when the entity is included in a federated response from another service

**Comment by abernix** [comment] 2022-08-19 09:19
@jmauerhan It doesn't sound like @Mithras was able to come up with a minimal reproduction, but I'm curious if you might be able to narrow things down to a set of subgraph SDL definitions and an operation to run against the composed supergraph of those subgraphs that might be able to reproduce this in isolation so we can look into it a bit more?

My only other suggestion of a way to help us debug this is if you could potentially get a more clear error message from running Apollo Gateway 2.x in place of the Router.  If that turns out to be helpful, we can then figure out why the error message isn't more helpful on the Router.

Could either of those be something you help us with?

We're happy to dig into this quickly with just a bit more information! Thanks!

**Comment by Mithras** [comment] 2022-08-19 16:42
I'm sure I can isolate if I spend some time on it. I'm not sure when I'll have time though. Can you suggest what's the easiest way to setup mock subgraphs with static json?

**Comment by abernix** [comment] 2022-08-19 17:36
@jmauerhan Interesting! There must be an error message that's getting swallowed here or something that could have proven helpful to you.

@Mithras If the requests aren't even making it to the subgraphs, I don't think you even need to go that far.  If you could just spin up the Apollo Gateway with the same Supergraph you're running on the Router and make the same query, you may be able to reproduce.

**Comment by abernix** [comment] 2022-09-01 10:13
@Mithras @jmauerhan do you think that https://github.com/apollographql/router/issues/1668 is possibly the same root cause that you're running into?  (In other words, does this go away if `__typename` is included?)

**Comment by abernix** [comment] 2022-09-07 10:57
I have reason to believe this will be fixed by #1698 and https://github.com/apollographql/router/pull/1711 so I'm going to mark it as closed.  We'll get a release cut today and you can validate after that release if this is still happening.

Thanks!

**Comment by Ugzuzg** [comment] 2022-09-08 08:27
Still an issue for me. I'll try to generate a reproducible example.

**Comment by Ugzuzg** [comment] 2022-09-08 13:05
Yes, it's `1.0.0-alpha.3`.

Here's a repo that reproduces the issue: https://github.com/Ugzuzg/apollo-router-deno-response

rover doesn't complain about anything while composing the supergraph.

**Comment by bnjjj** [comment] 2022-09-12 09:17
Should be fixed by https://github.com/apollographql/router/pull/1720

**Closed by bnjjj** 2022-09-12 09:17 UTC
Labels: triage, raised by user
