### ISSUE TITLE
Create custom binary via Github has unclear/broken dependencies

### ISSUE THREAD

**Issue by i-mann** [apollographql/router#1489] opened 2022-08-10 00:26 UTC
**Describe the bug**
When running a Github action to build a custom router binary, the job fails with a 404/missing dependency.

I've built a custom plugin to deploy with the router that simply authenticates a bearer token; this compiles successfully locally, and `cargo build --release --target x86_64-unknown-linux-gnu` successfully builds a release binary for the target architecture.

**To Reproduce**
* Using Router 0.14.0 (just saw 0.15.0 has been released; this has the same issue)
* Using GitHub action config
```
jobs:
  build-only:
      name: Build only
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: checkout
          uses: actions/checkout@v3
  
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: 1.61.0
            target: x86_64-unknown-linux-gnu
            override: true
            components: rustfmt
        
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 16
  
        - name: Cache Cargo
          uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --target x86_64-unknown-linux-gnu

```
See error/output below

**Expected behavior**
It builds :sweat_smile: 

**Output**
```
|    Compiling apollo-spaceport v0.14.0 (https://github.com/apollographql/router.git?tag=v0.14.0#9c0864ca)
| The following warnings were emitted during compilation:
| 
| warning: Updating router-bridge
| warning: running `npm ci`
| 
| error: failed to run custom build command for `router-bridge v0.1.0 (https://github.com/apollographql/federation-rs.git?branch=geal/defer#4cdcd574)`
| 
| Caused by:
|   process didn't exit successfully: `/home/imann/code/graphql/target/release/build/router-bridge-5d43838979a9e279/build-script-build` (exit status: 101)
|   --- stdout
|   cargo:rerun-if-changed=js-src
|   cargo:warning=Updating router-bridge
|   cargo:warning=running `npm ci`
| 
|   --- stderr
|   npm ERR! code E404
|   npm ERR! 404 Not Found - GET https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals
|   npm ERR! 404 
|   npm ERR! 404  '@apollo/federation-internals@https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals' is not in this registry.
|   npm ERR! 404 
|   npm ERR! 404 Note that you can also install from a
|   npm ERR! 404 tarball, folder, http url, or git url.
| 
|   npm ERR! A complete log of this run can be found in:
|   npm ERR!     /root/.npm/_logs/2022-08-09T04_51_31_557Z-debug-0.log
|   thread 'main' panicked at 'assertion failed: Command::new(&npm).current_dir(&current_dir).args(&[\"ci\"]).status().unwrap().success()', /root/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/4cdcd57/federation-2/router-bridge/build.rs:41:9
|   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
| warning: build failed, waiting for other jobs to finish...
```

**Desktop (please complete the following information):**
 - OS: Ubuntu-latest as per Github config

**Additional context**
I suspect this dependency issue is on [this branch in federation-rs](https://github.com/apollographql/federation-rs/tree/geal/defer) is causing the issue; whether it's because it doesn't build, or as an active branch it can't be referred to, I'm not sure.

**Comment by SHAMEL011** [comment] 2022-08-10 01:07
hey

**Comment by o0Ignition0o** [comment] 2022-08-10 07:10
Hi,

Thanks a lot for submitting such a thorough issue!

This issue looks like a duplicate of #1467. I recommend building against [0.15.0](https://github.com/apollographql/router/releases/tag/v0.15.0) which will compile.

I'm going to close it as duplicate, but feel free to reopen the issue if needs be!

**Closed by o0Ignition0o** 2022-08-10 07:10 UTC
Labels: triage, raised by user

**Comment by i-mann** [comment] 2022-08-11 00:38
Hi @o0Ignition0o, thanks for referencing #1467. 

Unfortunately pointing at geal/defer#721f1ff is failing in a local cargo build as well as a GitHub action. I can confirm that as per #1467 :
* router is pointing to 0.15.0
* `Cargo.toml` has 1 reference to router-bridge: `source = "git+https://github.com/apollographql/federation-rs.git?branch=geal/defer#72f1fff5e57a80b4ed4fcbf13ef2ac33b0314b80"`
* I've run `cargo update -p router-bridge` as suggested
* I'm on rust version 1.61.0

Is it preferred that I re-open this, or open an issue on federation-rs, or...? :) 

```  cargo:warning=running `npm run build`

  > @apollo/router-bridge@2.0.0-alpha.6 build /home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge
  > make-dir bundled js-dist && tsc && node esbuild/bundler.js

  js-src/plan.ts(56,37): error TS2345: Argument of type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/federation-internals/dist/definitions").Schema' is not assignable to parameter of type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/query-planner/node_modules/@apollo/federation-internals/dist/definitions").Schema'.
    Types of property 'blueprint' are incompatible.
      Property 'applyDirectivesAfterParsing' is missing in type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/federation-internals/dist/definitions").SchemaBlueprint' but required in type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/query-planner/node_modules/@apollo/federation-internals/dist/definitions").SchemaBlueprint'.
  js-src/plan.ts(139,41): error TS2345: Argument of type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/federation-internals/dist/operations").Operation' is not assignable to parameter of type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/query-planner/node_modules/@apollo/federation-internals/dist/operations").Operation'.
    The types of 'selectionSet.parentType' are incompatible between these types.
      Type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/federation-internals/dist/definitions").CompositeType' is not assignable to type 'import("/home/imann/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/72f1fff/federation-2/router-bridge/node_modules/@apollo/query-planner/node_modules/@apollo/federation-internals/dist/definitions").CompositeType'.
        Type 'ObjectType' is not assignable to type 'CompositeType'.
          Type 'ObjectType' is missing the following properties from type 'ObjectType': _unappliedDirectives, addUnappliedDirective, processUnappliedDirectives

// npm warn skipping optional dependencies

  npm ERR! code ELIFECYCLE
  npm ERR! errno 2
  npm ERR! @apollo/router-bridge@2.0.0-alpha.6 build: `make-dir bundled js-dist && tsc && node esbuild/bundler.js`
  npm ERR! Exit status 2
  npm ERR! 
  npm ERR! Failed at the @apollo/router-bridge@2.0.0-alpha.6 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by o0Ignition0o** [comment] 2022-08-11 06:32
Hmm this does not quite look like the 404 this issue surfaced.

@i-mann can you open an other one? This will allow us to focus on reproducing and fixing the one you raised.

I'll to reproduce it in the meantime

**Comment by o0Ignition0o** [comment] 2022-08-11 06:57
I just tried to build a custom router from a docker environment (so there's no ~/.cargo, sccache or ./target cache involved), and I've been able to build 0.15.1:

```
Compiling router-bridge v0.1.0 (https://github.com/apollographql/federation-rs.git?tag=defer-alpha1#72f1fff5)
   Compiling apollo-spaceport v0.15.1 (https://github.com/apollographql/router.git?tag=v0.15.1#ac7607b0)
   Compiling apollo-uplink v0.15.1 (https://github.com/apollographql/router.git?tag=v0.15.1#ac7607b0)
   Compiling apollo-router v0.15.1 (https://github.com/apollographql/router.git?tag=v0.15.1#ac7607b0)
   Compiling my_example v0.1.0 (/tmp)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 28s
```

Steps to reproduce:

1. Target `apollo-router` v0.15.1 in your `Cargo.toml` file

```toml
apollo-router = { git = "https://github.com/apollographql/router.git", tag = "v0.15.1" }
```

2. Run `cargo update -p apollo-router`

3. Note your Cargo.lock dependency now points to `tag=defer-alpha1`

```
[[package]]
name = "router-bridge"
version = "0.1.0"
source = "git+https://github.com/apollographql/federation-rs.git?tag=defer-alpha1#72f1fff5e57a80b4ed4fcbf13ef2ac33b0314b80"
dependencies = [
 "anyhow",
 "async-channel",
 "deno_core",
 "serde",
 "serde_json",
 "thiserror",
 "tokio",
 "tower",
 "tower-service",
 "tracing",
 "uuid 0.8.2",
 "which",
]
```

4. Perform a clean build: `cargo clean; cargo build`

Can you try to run the STRs I've mentioned above, and see if it works ?
I'm going to give it an other try using `--release` but I don't think this will have an impact.

**Comment by i-mann** [comment] 2022-08-11 23:37
Ah - there we go - working in Github actions. I've got some local weirdness going on, but I'll leave that for a full cache clear-out later. 

So - I was declaring the router-bridge version in my root Cargo.toml, and only Apollo router scaffold in xtask - not specifying explicitly the router version itself.

Interesting that the basic set-up documentation doesn't include this.

Thanks so much @o0Ignition0o !!

**Comment by o0Ignition0o** [comment] 2022-08-12 08:18
Glad it works in GH actions!

It's worth noting I run into all sort of weird things with local caches, especially when targeting git dependencies. so I tend to use [cargo-cache](https://crates.io/crates/cargo-cache) and run `cargo cache -a` every now and then. Hope it helps!
