### ISSUE TITLE
Share headers between subgraphs

### ISSUE THREAD

**Issue by endroca** [apollographql/router#2021] opened 2022-10-27 17:58 UTC
Propagation of headers occurs between client request -> subgraph.

is it possible to propagate a header from a subgraph to another subgraph internally (subgraph -> subgraph)? Without this header passing to the client.

```
An example would be to propagate a header containing the data of the user who has already been authenticated (I know it's not the best use case)
```

**Comment by lennyburdette** [comment] 2022-11-01 15:54
This is possible with rhai scripting and the shared context: 
```rhai
fn subgraph_service(service, subgraph) {
  let request_callback = |request| {
    if subgraph != "subgraph-one" {
      if request.context["value-from-subgraph"] != () {
        print(`Forwarding value ${request.context["value-from-subgraph"]} from ${subgraph}`);
        request.subgraph.headers["x-forwarded-value"] = request.context["value-from-subgraph"];
      }
    }

  };

  let response_callback = |response| {
    if subgraph == "subgraph-one" {
      print(`Will forward value ${response.headers["date"]} from ${subgraph}`);
      response.context["value-from-subgraph"] = response.headers["x-value-to-forward"];
    }
  };

  service.map_request(request_callback);
  service.map_response(response_callback);
}
```

**Comment by endroca** [comment] 2022-11-03 19:07
@lennyburdette, excellent, it helped me a lot... Is there any limit to the size of the header ? When the header is longer than 53 characters I'm getting this error

`map_response callback failed: Runtime error: failed to convert header to a str (line 15, position 57) in call to closure @ './rhai/main.rhai'`

**Comment by lennyburdette** [comment] 2022-11-03 20:31
Hmm I can't reproduce that error with router 1.2.1. Are there weird characters in your header values?

**Comment by endroca** [comment] 2022-11-04 13:18
@lennyburdette 

is a JSON string:

```
{"id":"...","name":"Andrew Simões","email":"...","company":{"id":"...","status":true},"role":...,"workspace":["...","...","..."],"plan":{"csTreatment":"PREMIUM","editors":500,"hasWinninReports":true,"jobs":500,"languages":["all","por","eng","spa"],"planEnd":"...","viewers":1000,"workspaces":1000,"channels":10,"savedPostSearches":10,"isActive":true},"kc":{"exp":...,"iat":...,"session_state":"...","sub":"..."}}
```

main.rhai
```
fn subgraph_service(service, subgraph) {
    let headers = ["request-id", "user", "pre-validate-user"];

    let request_callback = |request| {
        for key in headers {
            if request.context[key] != () {
                request.subgraph.headers[key] = request.context[key];
            }
        }
    };
  
    let response_callback = |response| {
        for key in headers {
            if key in response.headers {
                response.context[key] = response.headers[key];
            }
        }
    };
  
    service.map_request(request_callback);
    service.map_response(response_callback);
}
```

`print(response.headers);`
```
apollo_router::plugins::rhai: x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
pre-validate-user: {"success":true}
user: 
content-length: 78
etag: W/"4e-yIXPTyIeBJ01Q8VHUsG7QOi1ytM"
date: Fri, 04 Nov 2022 13:16:56 GMT
connection: keep-alive
keep-alive: timeout=5
```

I'm also in the version 1.2.1

**Comment by lennyburdette** [comment] 2022-11-04 13:52
It's not the length, it's the non-ascii character in `name: "Andrew Simões",`. i'll ping the router team about this.

**Comment by endroca** [comment] 2022-11-04 13:58
Transforming the data worked perfectly

Thank you very much @lennyburdette

**Comment by garypen** [comment] 2022-11-04 15:08
We could modify the header interaction functions within our `rhai` module so that they automatically `encode/decode` supplied header keys/values.

Does that sound useful?

**Comment by garypen** [comment] 2022-11-04 15:55
One more thought for now. I could encode/decode the values in the printed values. I didn't above just to illustrate that it was working. I imagine it would be clearer to encode/decode every time a human wants to interact with the header key/values.

**Comment by Geal** [comment] 2022-11-04 18:13
I don't think the router should do this automatically, especially for header names. That looks like something that should be handled manually in rhaiscript instead, by exposing the urlencode/urldecode functionq

**Comment by garypen** [comment] 2022-11-07 09:17
Usually, I'm all in favour of making things explicit. In this case, it does seem like we would want to make this conversion implicit and automatic for users. Reasoning:
 - it will always be invalid for HeaderMap key/values to be non-ascii. (where always == "a long time")
 - if this ever does become valid, we can simply remove the implicit encoding/decoding and life will continue

The only "con" I can think of is that users might, unknowingly, make mistakes by setting a header with a name or value containing what would be invalid characters (if not escaped). That's a good reason not to do this and, instead, to do as you suggest and require this conversion be explicit. It's going to be a real ux nuisance though, because if I was a user I'd always encode/decode all header keys and values "to be safe".

**Comment by Geal** [comment] 2022-11-07 10:36
the real UX nuisance will appear when someone has to debug why suddenly some headers are percent encoded, deep into a large infrastructure. Automagic solutions like these ones always end up creating other ones.

There's definitely a UX issue here though, but one that could be solved by having a more actionable error message than `map_response callback failed: Runtime error: failed to convert header to a str (line 15, position 57) in call to closure @ './rhai/main.rhai'`. Like a message telling that it will only accepts ASCII data, and here's the function to use to convert it.

**Comment by o0Ignition0o** [comment] 2022-11-07 10:50
Automagic encoding would be surprising to me as well, if this had to be done, I would rather have the subgraph do the percent encoding, or use rhai to patch my own router, instead of having this be the default behavior for everyone?

just my 2 cents

**Comment by garypen** [comment] 2022-11-07 12:06
Ok: I'm fine with requiring explicit behaviour. I just wanted to make sure we discussed all the ramifications before we move ahead. I'll raise a new issue: expose urlencode/decode functionality to rhai and do the work there.

**Comment by abernix** [comment] 2022-11-18 13:10
This was fixed in @garypen's https://github.com/apollographql/router/pull/2053.  We should add some documentation about this though. I'll open a new issue for that.

**Closed by abernix** 2022-11-18 13:10 UTC
Labels: triage, component/rhai, raised by user
