### ISSUE TITLE
Automated performance testing

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#78] opened 2021-07-06 19:20 UTC
> * Blocked by https://github.com/apollographql/router-perf-testing/issues/11

Automated daily performance tests.
First cut does not need to be complex, create something that we can add to.

**Comment by abernix** [comment] 2021-12-03 13:23
@BrynCooke What's the difference between this and #58 ?

**Comment by abernix** [comment] 2022-01-05 15:26
Duplicate of #58, which is closed.

**Closed by abernix** 2022-01-05 15:26 UTC
Labels: size/large, feature, 2021-12
