### ISSUE TITLE
APQ: Move the layer to a plugin

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1205] opened 2022-06-08 08:38 UTC
APQ is one of the few remaining layers; we want to make it a plugin.

While we're at it, it would be nice to investigate the Cache size aware eviction feature.

**Comment by tatsuya6502** [comment] 2022-06-09 04:59
Hi. Thank you for using Moka cache as the default in-memory cache for the APQ. Please feel free to ask me any questions about Moka and its size aware eviction feature. (I am the Moka author)

**Comment by o0Ignition0o** [comment] 2022-06-09 09:21
Hey, it's nice to meet you!

I sure will, thanks for your time :)

**Comment by abernix** [comment] 2022-08-12 08:07
Duplicate of #1125

**Closed by abernix** 2022-08-12 08:07 UTC
