### ISSUE TITLE
Add automation to release pipeline

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1121] opened 2022-05-20 16:00 UTC
As the prerelease checklist grows, bumping the router / core version everywhere became tedious and error prone.

It would be great if a cargo xtask command allowed us to:

- bump all of the versions (apollo router/core/xtask etc...)
- run cargo check so Cargo.lock gets updated
- update the dockerfiles
- update the helm chart
- update the compatibility matrix

- maybe even move the changelog around?
and more!

`cargo xtask bump X.X.X` would be nice!

**Comment by abernix** [comment] 2023-01-13 13:22
Duplicate of https://github.com/apollographql/router/issues/2261

... Which has more information now, so I'll close this in favor of that.

**Closed by abernix** 2023-01-13 13:22 UTC
Labels: component/infra
