### ISSUE TITLE
CPU consumption x4 since 1.21

### ISSUE THREAD

**Issue by utay** [apollographql/router#3309] opened 2023-06-22 16:53 UTC
We have seen a significant surge in CPU consumption on the router after the 1.21 upgrade, it approximately got multiplied by 4:
![2023-06-22-183551_1468x231_scrot](https://github.com/apollographql/router/assets/16670791/c51fe06a-8d4c-4409-9f12-de1e8b6b7d9a)

With the same code and plugins we reverted to 1.20 and it went back to normal. We didn't profile the router yet to find the culprit. Please let me know if you need more info!

**Comment by utay** [comment] 2023-06-23 06:56
Sorry, after some investigation, this CPU increase is due to one of our plugins and not related to the 1.21 upgrade. Closing

**Comment by utay** [comment] 2023-06-23 07:17
Re-opening the issue as a FYI. 

After some more investigation, the issue is a mix between one of our plugins where we do preprocessing of the HTTP body in `router_service` and this new code path added in 1.21:
```
    let compiler = match compiler {
        None =>
        // TODO[igni]: no
        {
            Arc::new(Mutex::new(
                QueryAnalysisLayer::new(schema, Default::default())
                    .await
                    .make_compiler(&query_str)
                    .0,
            ))
        }
        Some(c) => c,
    };
```

We go through the `None` branch. This explains the 4x CPU increase but you might be already aware looking at the comment :smile:

**Comment by Geal** [comment] 2023-06-23 07:57
hi @utay, could you show a reduced version of the plugin? That code path should only be triggered in tests, so I'd like to know how it happened for production queries

**Comment by utay** [comment] 2023-06-23 09:14
Hi @Geal, in a plugin we were doing something like this in `supergraph_service` - `checkpoint_async`:
```
    let (parts, body) = req.supergraph_request.into_parts();
    ...
    let req: supergraph::Request = http::Request::from_parts(parts, body).into();
```
which sets `compiler: None` and made us go through the heavy path in 1.21. 

We moved this logic in `router_service` - `checkpoint_async` which happens early enough in the request processing and should fix the issue. It's not yet deployed in production but I'll keep you posted on the results

**Comment by garypen** [comment] 2023-07-05 09:22
The issue is caused by the [highlighted change](https://github.com/apollographql/router/issues/3309#issuecomment-1603821188).

Investigation reveals that Supergraph requests which are created without a compiler will always have a compiler assigned to them for each request. If a request is cached, the compiler is cached, but a new compiler will be created and assigned before the cached request is retrieved. This whole process is repeated each time a request is made.

This is a CPU intensive operation and would easily account for the increase in CPU consumption.

The fix is, unfortunately, quite intrusive. I've worked up a draft PR which does mean that a compiler is only created once for each request. This eliminates the bug, but I'm not totally happy with the shape of the code. I'll work within the team to figure out a "nicer" way of achieving the same result.

**Comment by garypen** [comment] 2023-07-05 10:05
@utay Could you confirm that moving the code to `router_service` resolved the issue for you (it should, but polite to ask)?

**Comment by garypen** [comment] 2023-07-05 10:18
also: see #3373

**Comment by utay** [comment] 2023-07-05 13:52
@garypen Thank you for the details, this makes sense.

I confirm that moving the code to `router_service` resolved the issue for us

**Comment by garypen** [comment] 2023-07-05 14:28
Great. I'm going to close this for now and the underlying issue will continue to be tracked in #3373.

**Closed by garypen** 2023-07-05 14:28 UTC
Labels: raised by user
