### ISSUE TITLE
Propagate headers from between subgraphs via YAML config

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2444] opened 2023-01-20 11:53 UTC
This functionality is possible now via Rhai, however the purpose of this issue is to track if we should add the ability to do this via YAML.

https://www.apollographql.com/docs/router/customizations/rhai/

Rhai solution:
`main.rhai`
```
fn subgraph_service(service, subgraph) {
    let headers = ["request-id", "user"];

    let request_callback = |request| {
        for key in headers {
            if request.context[key] != () {
                request.subgraph.headers[key] = request.context[key];
            }
        }
    };
  
    let response_callback = |response| {
        for key in headers {
            if key in response.headers {
                response.context[key] = response.headers[key];
            }
        }
    };
  
    service.map_request(request_callback);
    service.map_response(response_callback);
}
```

The exact configuration of a yaml based solution will be discussed if enough users are in need of this functionality.

Please let us know if you'd like to see this by commenting on this issue.

Related to #2021

**Comment by abernix** [comment] 2023-02-08 20:58
Duplicate of #1284

**Closed by abernix** 2023-02-08 20:59 UTC
