### ISSUE TITLE
Regex for CORS origin config

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#965] opened 2022-05-05 14:37 UTC
Customer request: support regular expressions for the `origins:` key in the YAML config.

If the solution is to use Rhai, then a documented example would be sufficient!

**Comment by abernix** [comment] 2022-06-08 09:26
Duplicate of https://github.com/apollographql/router/issues/64

Thanks for opening this!

**Closed by abernix** 2022-06-08 09:26 UTC
Labels: triage, raised by user
