### ISSUE TITLE
Shareable queries cause alphabetical dependency

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#4580] opened 2024-02-01 19:54 UTC
**Describe the bug**

When a supergraph uses a query that multiple subgraphs can resolve (and annotated with `@shareable`), it'll run the root operation as a a parallel fetch via the query planner, which is desirable. 

However, if the first subgraph alphabetically returns an error (e.g. timeout), the entire object will fail _if_ there is a non-null field within, such as an ID field. 

**To Reproduce**

Using this sample graph:

```graphql
type Query {
  a: A! @shareable
}

type A @key(fields: "id") {
  id: ID!
  subgraph1: String
}
```

And creating N number of subgraphs (adding subgraph2, 3, etc), and then running: 

```
query A {
  a {
    subgraph1
    subgraph2
    subgraph3
  }
}
```

If the first alphabetical subgraph fails to load, the entire object fails. If it is not the first subgraph, the object returns normally. 

**Expected behavior**

The object returns with an errors key entry alongside the field being null if possible.

**Comment by lleadbet** [comment] 2024-02-02 15:38
This actually only happens in cases of timeouts, not errors. 

Example subgraph (handles all three subgraph requests):

```js
const gql = require("graphql-tag");
const { readFileSync } = require("fs");
const { ApolloServer } = require("@apollo/server");
const { buildSubgraphSchema } = require("@apollo/subgraph");
const { expressMiddleware } = require('@apollo/server/express4');
const http = require('http')
const express = require('express')
const { print } = require('graphql');
const port = process.env.PORT ?? 4002;

const resolvers = {
  A: {
    __resolveReference({ id }) {
      return { id };
    },
    subgraph1() {
      return "1"
    },
    subgraph2() {
      return "2"
    },
    subgraph3() {
      return "3"
    },
  },
  Query: {
    a() {
      return { id: 1 }
    }
  },
}
async function main() {
  const app = express();

  const typeDefs = gql(
    readFileSync("schema.graphql", {
      encoding: "utf-8",
    })
  );
  console.log(print(typeDefs))
  const server = new ApolloServer({
    schema: buildSubgraphSchema({ typeDefs, resolvers }),
  });
  await server.start()
  app.use('', express.json(), async (req, res, next) => {
    console.log(req.body)
    if (req.body.query.includes('subgraph1')) {
      await sleep(10000)
    }
    next()
  })
  app.use('/', express.json(), expressMiddleware(server));
  http.createServer({}, app).listen(port)
}

main();

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
```

Subgraph schema (schema.graphql in the code)

```gql
extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.0"
    import: ["@key", "@inaccessible", "@requires", "@external", "@shareable"]
  )

type Query {
  a: A! @shareable
}

type A @key(fields: "id") {
  id: ID!
  subgraph1: String
  subgraph2: String
  subgraph3: String
}
```

Finally the supergraph schema: 

```gql
schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION) {
  query: Query
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(
  graph: join__Graph
  requires: join__FieldSet
  provides: join__FieldSet
  type: String
  external: Boolean
  override: String
  usedOverridden: Boolean
) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(
  graph: join__Graph!
  interface: String!
) repeatable on OBJECT | INTERFACE

directive @join__type(
  graph: join__Graph!
  key: join__FieldSet
  extension: Boolean! = false
  resolvable: Boolean! = true
  isInterfaceObject: Boolean! = false
) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(
  graph: join__Graph!
  member: String!
) repeatable on UNION

directive @link(
  url: String
  as: String
  for: link__Purpose
  import: [link__Import]
) repeatable on SCHEMA

type A
  @join__type(graph: _1_, key: "id")
  @join__type(graph: _2_, key: "id")
  @join__type(graph: _3_, key: "id") {
  id: ID!
  subgraph1: String @join__field(graph: _1_)
  subgraph2: String @join__field(graph: _2_)
  subgraph3: String @join__field(graph: _3_)
}

scalar join__FieldSet

enum join__Graph {
  _1_ @join__graph(name: "1", url: "http://localhost:4002")
  _2_ @join__graph(name: "2", url: "http://localhost:4002")
  _3_ @join__graph(name: "3", url: "http://localhost:4002")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Query
  @join__type(graph: _1_)
  @join__type(graph: _2_)
  @join__type(graph: _3_) {
  a: A!
}
```

You will need to use the traffic_shaping timeout setting to set it  < 10s for purposes of demoing. 

If: 

`if (req.body.query.includes('subgraph1')) {`, the request fails the object entirely.

`if (req.body.query.includes('subgraph2')) {`, the request merges the results correctly. 

It entirely depends on the alphabetical ordering, so if you swap the graph enum to be:

```
enum join__Graph {
  _1_ @join__graph(name: "2", url: "http://localhost:4002")
  _2_ @join__graph(name: "1", url: "http://localhost:4002")
  _3_ @join__graph(name: "3", url: "http://localhost:4002")
}
```

(Note that subgraph 2 and 1 swapped)

And run:

```
query Use{
  a {
    id
    subgraph1
    subgraph2
  }
}
```

It now merges correctly, whereas:

```
query Use{
  a {
    id
    subgraph1
  }
}
```

Works as expected (full failure since 1 now fails fully).

**Comment by Geal** [comment] 2024-02-19 08:23
since we looked  at it off github and it was expected behavior by the planner, I will close this now

**Closed by Geal** 2024-02-19 08:23 UTC
Labels: raised by user
