### ISSUE TITLE
Memory leak in router

### ISSUE THREAD

**Issue by mohitd11** [apollographql/router#2981] opened 2023-04-21 10:38 UTC
**Describe the bug**
Apollo Router is not releasing the allocated memory.

**To Reproduce**
1. Expose apollo router to the traffic.
2. Stop the traffic.
3. When the traffic starts, there is a dip in available memory(which is expected), but when the traffic is stopped, allocated memory is not freed. The available memory dip still remains even when no traffic is flowing through apollo router.

**Expected behavior**
After the traffic is stopped, the allocated memory should be freed. 

**Output**
Below image shows the traffic pattern in the apollo router:
<img width="1579" alt="Screenshot 2023-04-21 at 3 46 50 PM" src="https://user-images.githubusercontent.com/122355974/233613122-96fffe30-7528-4fce-8e86-5982c01a0724.png">

Below image shows the available memory in the apollo router:
<img width="1013" alt="Screenshot 2023-04-21 at 3 57 21 PM" src="https://user-images.githubusercontent.com/122355974/233613812-9e5988e3-0a81-4d13-baaa-e5ac91e1ddf3.png">

As seen in the above images, the traffic starts around 20:00, and there is a dip in available memory, but when the traffic is stopped 20:30, the allocated memory is not freed. The available memory at this time is 65%.

Below image shows the TCP connection count:
<img width="1387" alt="Screenshot 2023-04-21 at 4 04 05 PM" src="https://user-images.githubusercontent.com/122355974/233615240-440ad87f-e66d-432b-8617-982d40810212.png">

**Desktop :**
 - OS: centos
 - Version: 7

**Additional context**
We are using apollo router version - 1.11.0

**Comment by abernix** [comment] 2023-04-21 17:30
The steps that you wrote aren't quite enough to reproduce this for me, but thank you for including the version that you're using.  Could you please update to the latest Router version and try again?  We've fixed a couple memory-leak related things since 1.11.0 (we're on 1.15.1, now) related to leaks in recent versions and this could be resolved by that.

(As a request, in general when reporting all bugs — especially memory leaks — please try to reproduce using the latest version first!).

**Comment by abernix** [comment] 2023-04-24 13:56
Related to the above, I should say that we _have_ observed something like this before and we _think_ we've improved some of it in recent releases.  Worth pointing out that in some of the other cases, we've seen that memory indeed _hasn't_ been aggressively freed, but instead has been getting freed in smaller amounts as new allocations are necessary.

Of course, this still isn't ideal.  We're looking at putting #2882 into a alpha release for folks to test, though you could [build it from source and try running it locally](https://github.com/apollographql/router/blob/dev/DEVELOPMENT.md#development-1), and we'd appreciate the validation if you're able to reliably reproduce what you're encountering.  We're staging some of that on https://github.com/apollographql/router/pull/2969 for an upcoming alpha.

**Comment by jutaz** [comment] 2023-05-02 09:52
We're running `1.15.1`, but we're also seeing some memory accumulation over time:
<img width="1477" alt="Screenshot 2023-05-02 at 12 50 57" src="https://user-images.githubusercontent.com/1277553/235635472-e2fd8483-10b1-45da-ac55-adce0a165c8c.png">

You'll notice that at some point it reaches ~100% at which point k8s tells the pod to restart, which takes the memory usage back down.

Unsure what specifically might be causing this, though. Happy to provide more details if that would be helpful.

**Comment by garypen** [comment] 2023-07-01 12:39
I think this has been fixed by our change to use jemalloc: #2882. Please re-open if there is still an issue.

**Closed by garypen** 2023-07-01 12:39 UTC
Labels: raised by user
