### ISSUE TITLE
CORS error on quickstart

### ISSUE THREAD

**Issue by vvakame** [apollographql/router#124] opened 2021-11-11 02:38 UTC
**Describe the bug**
I tried https://www.apollographql.com/docs/router/quickstart/ this document.
But I can't make query properly.

**To Reproduce**
1. Download https://github.com/apollographql/router/releases/download/v0.1.0-alpha.0/router-0.1.0-alpha.0-x86_64-macos.tar.gz
2. tar -xf ./router-0.1.0-alpha.0-x86_64-macos.tar.gz
3. cd dist
4. curl -L https://supergraph.demo.starstuff.dev/ > starstuff.graphql
5. ./router --supergraph starstuff.graphql
6. open http://127.0.0.1:4000
7. redirect to https://studio.apollographql.com/sandbox/explorer
8. IntrospectionQuery failed by `OPTIONS http://127.0.0.1:4000/` become 403 error

**Expected behavior**
We can post query to router hosted graph.

**Output**

```
$ ./router --supergraph starstuff.graphql
Nov 11 11:22:44.986  INFO router: Starting Apollo Router
*******************************************************************
⚠️  Experimental software, not YET recommended for production use ⚠️
*******************************************************************
Nov 11 11:22:45.107  INFO router: Listening on http://127.0.0.1:4000 🚀
```

<img width="1698" alt="Explorer___Sandbox___Studio" src="https://user-images.githubusercontent.com/125332/141226388-5526975d-4fc6-4d5c-a9b4-810542781640.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Version [e.g. 22] 11.6 (20G165)

**Additional context**
None.

**Comment by o0Ignition0o** [comment] 2021-11-12 10:23
Hi @vvakame, thanks for opening an issue!

![image](https://user-images.githubusercontent.com/9465678/141449904-d523119d-75a9-45aa-901f-7b0103cea646.png)

I can't seem to reproduce it on my end, could you please paste the OPTIONS request that is being performed, as well as the headers that are being passed?

**Comment by vvakame** [comment] 2021-11-18 11:02
@o0Ignition0o here is it!
I got 403 error on OPTIONS request.

POST + preflight

<img width="2044" alt="POST___preflight" src="https://user-images.githubusercontent.com/125332/142402730-04cc41a3-fe36-4323-9703-3c4f4d3cd992.png">

OPTIONS

<img width="2038" alt="OPTIONS" src="https://user-images.githubusercontent.com/125332/142402625-b6b379bb-080b-42ad-91d1-b3cb359cb57f.png">

I talked with my colleague. they said they didn't meet the same problems...

**Comment by o0Ignition0o** [comment] 2021-11-22 10:00
Ok so the way I would debug this would be by enabling log traces on the router, and performing raw curl requests:

```sh
$ ./router --log=trace --supergraph starstuff.graphql
```

and in an other terminal:

```sh
$ curl http://127.0.0.1:4000 \
   -X OPTIONS \
   -H "Access-Control-Request-Method: POST" \
   -H "Access-Control-Request-Headers: content-type" \
   -H "Origin: http://localhost"
```

This request doesn't fail, but If i remove the Origin header, i will see logs that look like this:

```sh
$ curl http://127.0.0.1:4000 \
   -X OPTIONS \
   -H "Access-Control-Request-Method: POST" \
   -H "Access-Control-Request-Headers: content-type"
```

```sh
Nov 22 10:55:41.917 TRACE hyper::proto::h1::conn: Conn::read_head
Nov 22 10:55:41.917 TRACE hyper::proto::h1::io: received 165 bytes
Nov 22 10:55:41.917 TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=165
Nov 22 10:55:41.917 TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(165)
Nov 22 10:55:41.918 DEBUG hyper::proto::h1::io: parsed 5 headers
Nov 22 10:55:41.918 DEBUG hyper::proto::h1::conn: incoming body is empty
Nov 22 10:55:41.918 TRACE warp::filters::method: method::GET?: OPTIONS
Nov 22 10:55:41.918 TRACE warp::filters::method: method::POST?: OPTIONS
Nov 22 10:55:41.918 DEBUG warp::filter::service: rejected: Rejection([MethodNotAllowed, MethodNotAllowed])
Nov 22 10:55:41.918 TRACE encode_headers: hyper::proto::h1::role: Server::encode status=405, body=Some(Known(23)), req_method=Some(OPTIONS)
Nov 22 10:55:41.918 TRACE hyper::proto::h1::io: buffer.queue self.len=133 buf.len=23
Nov 22 10:55:41.918 DEBUG hyper::proto::h1::io: flushed 156 bytes
Nov 22 10:55:41.918 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
```

In the logs you can see that CORS rejected the call. It says method not allowed but it turns out an Origin header is required.

There might be a difference between the headers sent by your browser and the other ones.

**Comment by vvakame** [comment] 2021-11-25 02:07
Ah, I found the root cause.
I used https://studio.apollographql.com/sandbox/explorer what I forgot to set various settings for research long ago...

```
$ curl http://127.0.0.1:4000 -X OPTIONS -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: apollo-federation-include-trace," -H "Origin: https://studio.apollographql.com" -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 4000 (#0)
> OPTIONS / HTTP/1.1
> Host: 127.0.0.1:4000
> User-Agent: curl/7.64.1
> Accept: */*
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: apollo-federation-include-trace,
> Origin: https://studio.apollographql.com
>
< HTTP/1.1 403 Forbidden
< content-type: text/plain; charset=utf-8
< content-length: 42
< date: Thu, 25 Nov 2021 02:05:46 GMT
<
* Connection #0 to host 127.0.0.1 left intact
CORS request forbidden: header not allowed* Closing connection 0
```

<img width="577" alt="Explorer___Sandbox___Studio" src="https://user-images.githubusercontent.com/125332/143365042-c95e3fec-1445-4576-ae1c-6f1bf4a7bfad.png">

**Comment by o0Ignition0o** [comment] 2021-11-29 17:00
This is good news!

Extra headers would require a configuration setting as explained [here](https://www.apollographql.com/docs/router/configuration/#configuration-file).

I'm closing this issue, feel free to reopen it if needs be!

**Closed by o0Ignition0o** 2021-11-29 17:00 UTC
Labels: triage
