### ISSUE TITLE
error[E0080]: evaluation of constant value failed

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#3672] opened 2023-08-25 06:37 UTC
**Describe the bug**
Seeing these errors since last night. No changes on our side, this just started failing. Probably some unpinned dependency.

```sh
error[E0080]: evaluation of constant value failed
    --> /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.71.2/src/isolate.rs:1715:3
     |
1715 |   assert!(size_of::<TypeId>() == size_of::<u64>());
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: size_of::<TypeId>() == size_of::<u64>()', /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.71.2/src/isolate.rs:1715:3
     |
     = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
     
...


For more information about this error, try `rustc --explain E0080`.
error: could not compile `v8` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `v8` (lib) due to previous error
```

Any ideas?

**Comment by Meemaw** [comment] 2023-08-25 06:38
I see this is failing in your repo as well ~ on the latest PR: https://github.com/apollographql/router/pull/3671

**Comment by Meemaw** [comment] 2023-08-25 06:56
Seems to be due to Rust 1.72.0

**Comment by abernix** [comment] 2023-08-28 09:37
Thanks for opening this!  I'll close this as a duplicate of #3684, which has a reproduction.

**Closed by abernix** 2023-08-28 09:37 UTC
Labels: raised by user
