### ISSUE TITLE
Expose sha256 function to rhai script

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2112] opened 2022-11-16 07:54 UTC
**Is your feature request related to a problem? Please describe.**
We are using a variant of persisted queries. Clients will send sha256 query signature within a request header, and the server validates that this matches the request body, and rejects the query otherwise.

With federation we cannot do that on the subgraphs anymore, because the query that is sent to subgraphs is modified so the signature obviously won't match.

**Describe the solution you'd like**
It's already possible to access request body, and headers within a rhai script, but the missing part is the `sha256` function/module.

**Describe alternatives you've considered**
N/A

**Additional context**
I think exposing `sha256` might be useful for other usecases as well.

**Comment by abernix** [comment] 2022-11-18 19:21
Thanks for opening this Let's go ahead and track this in the existing #2025, which is essentially trying to capture the same thing.  Please do add your use-case concretely for SHA256 (though that was definitely inclusive of my consideration when I opened it).

Duplicate of https://github.com/apollographql/router/issues/2025?

**Closed by abernix** 2022-11-18 19:21 UTC
Labels: triage, component/rhai, raised by user
