### ISSUE TITLE
error: one of the values isn't valid for an argument

### ISSUE THREAD

**Issue by namikazebadri** [apollographql/router#4073] opened 2023-10-21 10:08 UTC
Hi, when i run ./router in my local computer, i got this:

**error: one of the values isn't valid for an argument**

I don't know what was causing this error, because it is okay a while ago.

Thank you,

**Comment by garypen** [comment] 2023-10-21 11:02
Could you provide:
platform os: 
router version:
exact command line and error:
configuration file(if present):
?
We can then try to help you.

**Comment by Roshan-R** [comment] 2023-11-14 15:10
Could be a duplicate of this: https://github.com/apollographql/router/issues/3023

**Comment by abernix** [comment] 2023-11-27 10:27
Thank you for offering the suggestion, @Roshan-R.  I suspect it probably is.  Given that we haven't heard back from @namikazebadri, I'm going to close this for now, but happy to re-open if the problem is actually different.  Thanks!

**Closed by abernix** 2023-11-27 10:27 UTC
Labels: raised by user
