### ISSUE TITLE
Access-Control-Allow-Origin header missing

### ISSUE THREAD

**Issue by krisztian-sala** [apollographql/router#792] opened 2022-04-05 11:59 UTC
**Describe the bug**
If the `Origin` header is not set in the request, the `access-control-allow-origin` will be missing from the response, even though `allow_any_origin` is set to true.
This causes CORS issues with our clients.

With Apollo server, the header was sent with every response, even when the Origin header was not set in the request.
Can't decide if the new behavior is a bug or a feature.
**To Reproduce**
1. Start Apollo router
2. Set `allow_any_origin` to true
3. Send a request to the router
4. Check the response headers. `access-control-allow-origin` will be missing

**Expected behavior**
`access-control-allow-origin: *` will be present in all responses if the `allow_any_origin` is set to true

**Comment by o0Ignition0o** [comment] 2022-04-05 13:40
Hi, thanks for filing the issue!

It indeed looks like a bug, i'll try to reproduce it

**Comment by bnjjj** [comment] 2022-04-07 16:23
After some investigations, the bug is coming from `warp`, there are already several issues and also 1 opened PR but it's opened for 2 years therefore I think it won't be fixed tomorrow. BTW we plan to migrate to Axum, apparently axum has the same issue haha but the issue is pretty new and there is a PR in progress. I think it sounds reasonable to wait for the fix on axum and keep the #751 PR up to date with main to be ready when axum has been released with this fix.

**Comment by BrynCooke** [comment] 2022-04-08 14:36
@bnjjj How difficult is it for us to put in a stop gap solution?

**Comment by bnjjj** [comment] 2022-04-08 14:47
I updated the axum branch to be compliant with the current main, all tests are passing now https://github.com/apollographql/router/pull/751 we just need to check if the perf tests are OK. After that the PR on tower-http is ready to review so I think it will be quickly merged, and we will just need to upgrade the axum version to benefit from all of these fixes. We also could also try to trick the cors configuration and override the behavior with a custom middleware but I really think we will have this fix upstream pretty quickly

**Comment by BrynCooke** [comment] 2022-04-13 12:50
@bnjjj Now that Axum is merged is this fixed as long as the Axum feature was enabled at compile time?

**Comment by bnjjj** [comment] 2022-04-13 13:17
Not yet, waiting for https://github.com/tower-rs/tower-http/pull/237

**Closed** 2022-05-02 08:40 UTC
Labels: bug, raised by user
