### ISSUE TITLE
Fix perf issue

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#397] opened 2022-02-04 09:13 UTC
Initiallly the concern was a memory leak on the tower branch, but it looks like this is also present on main.

**Comment by Geal** [comment] 2022-02-07 15:59
this might be linked to https://github.com/hyperium/hyper/issues/1790 but it is hard to debug, I'll look into it after checking the other issues

**Comment by o0Ignition0o** [comment] 2022-02-11 13:08
Closing this because we cannot reproduce.

**Closed by o0Ignition0o** 2022-02-11 13:08 UTC
