### ISSUE TITLE
v1.20.0: Unexpected query planner behavior with fragments within an interface (`Cannot add fragment of condition "..." to parent type "..."`)

### ISSUE THREAD

**Issue by utay** [apollographql/router#3227] opened 2023-06-06 17:21 UTC
I'm using Apollo router 1.20.0 and the query planner fails unexpectedly with the following error:
{
      "message": "value retrieval failed: router bridge error: the deno runtime raised an error: `request: couldn't receive response couldn't deserialize payload `10037068933640391434`: `deno: couldn't deserialize response : `Error(\"invalid neither null nor empty object: found Object {\\\"code\\\": String(\\\"QUERY_PLANNING_FAILED\\\"), \\\"exception\\\": Object {\\\"stacktrace\\\": Array [String(\\\"Cannot add fragment of condition \\\\\\\"BaseballCard\\\\\\\" (runtimes: [BaseballCard]) to parent type \\\\\\\"NBACard\\\\\\\" (runtimes: NBACard)\\\")]}}\", line: 0, column: 0)``.`",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }

<details>
<summary>Query to reproduce</summary>

```
{
  nbaCard {
    ...Fragment1
  }
}

fragment Fragment1 on CardInterface {
  other {
    ... on NBACard {
      id
    }
    ... on BaseballCard {
      id
    }
  }
}
```
</details>

<details>
<summary>Minimal supergraph to reproduce</summary>

```
schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
{
  query: Query
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

type BaseballCard implements CardInterface
  @join__implements(graph: BACKEND, interface: "CardInterface")
  @join__type(graph: BACKEND)
{
  id: Int!
  other: BaseballCard!
}

interface CardInterface
  @join__type(graph: BACKEND)
{
  id: Int!
  other: CardInterface!
}

scalar join__FieldSet

enum join__Graph {
  BACKEND @join__graph(name: "backend", url: "http://localhost:3000")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type NBACard implements CardInterface
  @join__implements(graph: BACKEND, interface: "CardInterface")
  @join__type(graph: BACKEND)
{
  id: Int!
  other: NBACard!
}

type Query
  @join__type(graph: BACKEND)
{
  nbaCard: NBACard!
}
```
</details>

I'm not sure it's valid graphql as the query to the subgraph directly returns an empty object while I expect it to return an object with `id` but at least it should not crash in the router

**Comment by utay** [comment] 2023-06-06 17:23
FYI @abernix @pcmanus another query planner error

**Comment by abernix** [comment] 2023-06-06 18:39
Thanks.  Our query planner team is on it, but I'll leave this issue here.  Probably a duplicate of https://github.com/apollographql/router/issues/3217.

**Comment by abernix** [comment] 2023-06-13 10:12
Just as an update, we are still awaiting a fix from the upstream team responsible for this.  They are going about doing some additional, but time-consuming/painstaking, validations (both automated and manually) that we hope will more concretely resolve that the issues which have recurrently impacted fragments in recent versions.  Furthermore, my understanding that is that we have identified the root cause which led these to get through our fully-automated testing in the first place and are working to resolve those, as well.

Thank you for your patience!

**Comment by utay** [comment] 2023-06-13 13:32
Thank you for the update @abernix :pray:

**Comment by BrynCooke** [comment] 2023-06-20 10:57
Fixed in https://github.com/apollographql/router/releases/tag/v1.21.0

**Closed by BrynCooke** 2023-06-20 10:57 UTC
Labels: raised by user
