### ISSUE TITLE
Packaging issue with v1.0.0-alpha.0 

### ISSUE THREAD

**Issue by deweyjose** [apollographql/router#1657] opened 2022-08-30 22:03 UTC
By default v1.0.0-alpha.0 does not compile.  The dependency on router-bridge is incorrect - v0.1.0 instead of  v0.1.0-alpha.1.

I updated my Cargo.toml to use `1v1.0.0-alpha.0`

```
   Compiling apollo-router v1.0.0-alpha.0 (https://github.com/apollographql/router.git?tag=v1.0.0-alpha.0#d5e64069)
error[E0432]: unresolved import `router_bridge::planner::DeferStreamSupport`
 --> /Users/rj757l/.cargo/git/checkouts/router-18de2f110854a520/d5e6406/apollo-router/src/introspection.rs:6:5
  |
6 | use router_bridge::planner::DeferStreamSupport;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `DeferStreamSupport` in `planner`

error[E0432]: unresolved import `router_bridge::planner::DeferStreamSupport`
 --> /Users/rj757l/.cargo/git/checkouts/router-18de2f110854a520/d5e6406/apollo-router/src/query_planner/bridge_query_planner.rs:8:5
  |
8 | use router_bridge::planner::DeferStreamSupport;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `DeferStreamSupport` in `planner`

error[E0560]: struct `QueryPlannerConfig` has no field named `defer_stream_support`
  --> /Users/rj757l/.cargo/git/checkouts/router-18de2f110854a520/d5e6406/apollo-router/src/introspection.rs:61:17
   |
61 |                 defer_stream_support: Some(DeferStreamSupport {
   |                 ^^^^^^^^^^^^^^^^^^^^ `QueryPlannerConfig` does not have this field
   |
   = note: available fields are: `incremental_delivery`

error[E0560]: struct `QueryPlannerConfig` has no field named `defer_stream_support`
  --> /Users/rj757l/.cargo/git/checkouts/router-18de2f110854a520/d5e6406/apollo-router/src/query_planner/bridge_query_planner.rs:54:25
   |
54 |                         defer_stream_support: Some(DeferStreamSupport {
   |                         ^^^^^^^^^^^^^^^^^^^^ `QueryPlannerConfig` does not have this field
   |
   = note: available fields are: `incremental_delivery`

```

Projects generated by the apollo router scaffold also have this issue - v1.0.0-alpha.0 apollo-router depdencies with router-bridge v0.1.0 dependency.

I was able to work around this by updating the dependency manually:

`cargo update -p router-bridge --precise 0.1.0-alpha.1`

**Comment by abernix** [comment] 2022-08-31 06:32
Interesting.  Thanks for reporting this! This might have started happening _after_ the `1.0.0-alpha.0` release since we published [a non-alpha `0.1.0` yesterday](https://crates.io/crates/router-bridge/versions) (so about 18 hours back from when i'm writing this).

Does Rust's variation of semver automatically bump to `0.1.0` if the specifier was `0.1.0-alpha.1` or something?

**Comment by Geal** [comment] 2022-08-31 07:50
sorry, this is not very clear, could you show us your `Cargo.toml` so we know which dependencies you are importing? Are you using the router from the published tag or from a commit?

**Comment by abernix** [comment] 2022-08-31 11:15
I wasn't able to use `cargo-scaffold` because of [my own reason](https://github.com/iomentum/cargo-scaffold/issues/30) but I was able to reproduce the above by merely copying the templates out of https://github.com/apollographql/router/tree/main/apollo-router-scaffold/templates/base and manually filling in the `{{ handle bar templates }}` in the two `Cargo.toml` files.

I pushed it up here: https://github.com/abernix/repo-apollographql-router-issue-1657

**Comment by Geal** [comment] 2022-08-31 12:53
@deweyjose so this is an unfortunate consequence of semver matching in Cargo: 0.1.0-alpha.0 is compatible with 0.1.0, and Cargo dependencies that only specify a version allow the upgrade to another compatible version. Since the scaffolded project does not come with a `Cargo.lock`, cargo will take the highest available version.

This will be fixed in the next router release, which should happen in the next few days. In the meantime, if you specify the dependency on the router to [this commit](https://github.com/apollographql/router/commit/d0cab772501db3d8e3a3e0de07a3929968f640fd) or any more recent commit, it will compile properly

**Comment by abernix** [comment] 2022-09-02 11:24
We believe this will be fixed when https://github.com/apollographql/router/pull/1689 releases, which should be in the next hour or so.  Thanks for your patience!

**Comment by abernix** [comment] 2022-09-02 14:13
[The `v1.0.0-alpha.1` release is out](https://github.com/apollographql/router/releases/tag/v1.0.0-alpha.1) — we hope this is resolved!

Using my reproduction — which used the `cargo scaffold` workflow — I had to run `cargo update` inside the `xtask` directory to bump the `clap` dependency, but it worked perfect after that:

https://github.com/apollographql/router/blob/b79d915622de446d856c402f1682c997e74b8fbe/apollo-router-scaffold/templates/base/xtask/Cargo.toml#L20

**Closed by abernix** 2022-09-02 14:13 UTC
Labels: triage, raised by user

**Comment by deweyjose** [comment] 2022-09-02 15:53
thanks all!
