### ISSUE TITLE
Allow using and preserve operation names in the request path in the federated gateway

### ISSUE THREAD

**Issue by martin-dd** [apollographql/router#146] opened 2021-11-16 03:25 UTC
**Is your feature request related to a problem? Please describe.**
To increase observability by components which do not understand GraphQL we are using explicit operation names in the actual path we use to execute the GraphQL request. For example in order to retrieve a shopping cart we use `GetCart` operation and it is sent to `https://gql-gateway.company.com/graphql/GetCart` URL. Another operation would use a different path - e.g. `GetStores` is sent to `https://gql-gateway.company.com/graphq/GetStores` URL. 

Using this convention allow us to greatly increase observability in components which do not understand GraphQL, but have great support for regular REST calls. 

This system works well with our Spring Boot based GraphQL server and it would be great if we could add this to the federated gateway. 

**Describe the solution you'd like**
It would be great if Federated gateway would allow to accept requests with operation name in their path. It would be also great if it would optionally continue to send the requests with this operation name in the path to the subgraphs. 

**Describe alternatives you've considered**
Apollo clients send `X-APOLLO-OPERATION-NAME` header with the operation name, unfortunately this is not enough for our existing monitoring tools/systems, which have been built mostly for REST traffic. 

**Additional context**

**Comment by hsblhsn** [comment] 2022-01-05 18:44
We do that on the JS gateway. It would be great if the router supports this feature and makes the header name configurable.

**Comment by abernix** [comment] 2022-01-07 11:15
@hsblhsn: It sounds like you'd be fine with the operation name to http header approach, is that right?

For example: `query MyOperation { ... }` would result in a `apollo-operation-name: MyOperation` header to the subgraph.

(I'm asking for clarification because you 👍'd up this, but @martin-dd noted that a header-based solution was _not_ suitable for them. 😄 )

**Comment by hsblhsn** [comment] 2022-01-07 11:21
I am okay with the header based solution or the operation name based solution @martin-dd suggested. I just want to receive the operation name in the subgraph. 

And I prefer @martin-dd's proposal.

**Comment by abernix** [comment] 2022-01-07 12:29
Thanks, @hsblhsn!

For the both of you, while I realize that you may have baked in this behavior to existing clients that you can potentially not change — it was implied to me that existing REST-traffic-based systems wouldn't be able to observe HTTP headers in a meaningful way, I'm curious if the [`operationName` query string parameter](https://graphql.org/learn/serving-over-http/#get-request) (which is used to negotiate which operation to execute when there is more than one operation in a document) might be something that is easily observed by your existing REST systems?

And as a follow-up to that, in the case where there were multiple GraphQL operations in a document, what would be the expected behavior if an operation was sent with both `GetStores` and `GetCart` operations and an `operationName` of `GetCart` to the `/graphql/GetCart` endpoint?  (It is possible that you do not do this by convention, but it would seem we need to be considerate of this when imagining a solution.)

**Comment by abernix** [comment] 2023-01-20 08:55
I'm going to close this because we believe this can be done with Rhai scripting at this point. I'd suggest taking a [look at our `examples` directory](https://github.com/apollographql/router/tree/main/examples) and see if you can find the right combination of things and reporting back if you find it's problematic.

**Closed by abernix** 2023-01-20 08:55 UTC
Labels: triage, raised by user
