### ISSUE TITLE
Consider adding jwt validation config

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3329] opened 2023-06-28 09:03 UTC
Follow up to #3224 
Consider adding the following functionality to JWTs so that users don't have to write a rhai script.
```
authentication:
  jwt:
    require_authentication: true
    require_claims: # Fail the request if claims were missing
      - a
      - b 
    propagate_claims: http_headers | graphql_extension # Propagate the claims as http headers or graphql extensions.
```
This needs design though.

**Comment by Geal** [comment] 2023-06-28 12:46
related to https://github.com/apollographql/router/issues/2867

**Comment by Geal** [comment] 2024-01-15 10:25
closing as duplicate of #2867

**Closed by Geal** 2024-01-15 10:25 UTC
