### ISSUE TITLE
update cargo-deny entries with Elastic-2.0

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#450] opened 2022-02-11 14:52 UTC
[spdx 0.8.1 is out!](https://github.com/EmbarkStudios/spdx) this means we might be able to update our license entries with `Elastic-2.0`.

Let's have a close look at cargo-deny and update it when we can!

**Comment by abernix** [comment] 2022-05-02 11:39
Duplicate of #418.

**Closed by abernix** 2022-05-02 11:39 UTC
Labels: triage
