### ISSUE TITLE
Unable to update response in router_Service using body

### ISSUE THREAD

**Issue by xsoufiane** [apollographql/router#1403] opened 2022-07-15 11:31 UTC
Sorry If I put this in the wrong issue category 🙏  I didn't know how to classify it

**Is your feature request related to a problem? Please describe.**
In the case of a ValidationInvalidTypeVariable error where the request is not forwarded to the subgraphs, we wanna change the status code from 200 to 400. Only way we see to do this is to check the response in the *router_service* part and update it, but we have trouble achieving this because of the async/stream nature of the response.

**Describe the solution you'd like**
We wanna be able to change the response status if the response, wasn't forwarded to the subgraphs, and contains a specific error. 

**Describe alternatives you've considered**
- 1st approach: I taught about using *map_response* to set the context and *and_then* to change the response by using something like: 
```
let context = Arc::new(Mutex::new(res.context.clone()));

let res = res
  .map(|stream| {
    let context = context.clone();
    stream.map(move |item| {
      for err in &item.errors {
          if let Some(err_type) = err.extensions.get("type") {
              if err_type == "ValidationInvalidTypeVariable" {
                  let _ = context
                      .lock()
                      .unwrap()
                      .insert::<&str, u16>("status_code", 400);
              }
          }
      }

      item
  })
})
.boxed();

RouterResponse {
  context: Arc::unwrap_or_clone(context),
  ..res
}
```
but the context in the RouterResponse is not an arc 😞
- 2nd approach:  I also tried consuming the response in *and_then* with next() but I had trouble creating another stream of responses, and peekable didn't compile 😞 . I taught about creating a single response by supposing the streams contains a single response but that doesn't seem to be a reliable solution.

**Comment by o0Ignition0o** [comment] 2022-07-22 16:42
Hey @xsoufiane , sorry for the delay

Please find [here an example I've just written](https://github.com/o0Ignition0o/quick-stream-example/tree/igni/custom_http_response_status)

This example retrieves subgraph responses, and uses the context to set an intent to change the status code.
The router_service part of the plugin then reads the context, and updates the status code accordingly.

With that in mind I believe you can use [the router_service machinery](https://github.com/o0Ignition0o/quick-stream-example/blob/898a55e1035804cb6dd8b882ad1394419c5d25bc/src/plugins/test_plugin.rs#L43) that updates the response status_code.

This however wouldn't solve the second issue, which is the fact you want to see the first chunk in order to set the http_status.

It's worth noting `ValidationInvalidTypeVariable` is a spec error that happens during query planning.

This means you could possibly edit the example I mentioned above, and hook at the query_planner service to set the context as intended.

I'll have to have a better look at #1158 and try to reproduce it locally, but I hope it helps you make some progress in the meantime!

**Comment by o0Ignition0o** [comment] 2022-07-22 19:11
Ok here goes!

Here's a [query_plan error catcher that intercepts InvalidType errors and turns them into 401s!](https://github.com/o0Ignition0o/quick-stream-example/blob/69ba57a301616c4ac0fda182d00698e6fa857d17/src/plugins/test_plugin.rs#L67)

Note it's a fairly advanced example, and [we hope we can figure out a more simple API to deal with query planner errors ](https://github.com/apollographql/router/issues/1142)

Here are a couple of tricks I've used:
- Since we're dealing with BoxError, I've had to [Downcast them](https://doc.rust-lang.org/std/any/trait.Any.html#method.downcast_ref)
- Since errors provide BoxError only, I had to map_future_with_context, so I could keep the context around
- Plugins are [easy to test](https://github.com/o0Ignition0o/quick-stream-example/blob/69ba57a301616c4ac0fda182d00698e6fa857d17/src/plugins/test_plugin.rs#L133), thanks to provided service methods
- The main.rs file contains [usage instructions](https://github.com/o0Ignition0o/quick-stream-example/blob/69ba57a301616c4ac0fda182d00698e6fa857d17/src/main.rs#L1), as well as a curl example with a [valid query](https://github.com/o0Ignition0o/quick-stream-example/blob/69ba57a301616c4ac0fda182d00698e6fa857d17/src/main.rs#L35), and an other one with an[ invalid one ](https://github.com/o0Ignition0o/quick-stream-example/blob/69ba57a301616c4ac0fda182d00698e6fa857d17/src/main.rs#L3)

Hope it helps, while we're trying to come up with an easier to use api!

**Comment by o0Ignition0o** [comment] 2022-07-25 15:22
I just discussed this with @SimonSapin, and it turns out query planner errors do return http 400 by default.

@xsoufiane I m going to close this issue since what you're expecting is now default behavior (i ve just tested using router 0.12)

**Comment by xsoufiane** [comment] 2022-07-27 11:30
thank you @o0Ignition0o for the feedback, and examples I'm sure they will be helpful for us in the future :) I will also rerun the test to double check this with the latest version

**Comment by xsoufiane** [comment] 2022-07-27 21:36
@o0Ignition0o  I just tested with v0.12.0 and the query is:
```
When I post(s"${wsConfig.graphQLBaseURL}/<project-key>/graphql").withBody(
  """
    {
      "query": "query getCustomer($key: String!) { customer(key: $key) { id } }",
      "variables": {}
    }
  """
)
```
 but I still get 200 with: 
```
 {
    "errors" : [
      {
        "message" : "invalid type for variable: 'key'",
        "locations" : [
        ],
        "path" : null,
        "extensions" : {
          "type" : "ValidationInvalidTypeVariable",
          "name" : "key"
        }
      }
    ]
  }
```

**Comment by o0Ignition0o** [comment] 2022-08-19 15:44
Hey, sorry this went under my radar, given the issue is closed.

I'm not quite sure my initial diagnostics is correct anymore, given the body you are sending is indeed missing the $key variable.

I'll have to think a bit more about it.

**Comment by o0Ignition0o** [comment] 2022-08-19 15:55
Just reproduced it, this can be reproduced using the demo schema, and querying

```
query TopProducts($first: Int) {
  topProducts(first: $first) {
    price
  }
}
```

with variables:
```
{
  "first": "hello"
}
```

This will return a 200 with errors, which is expected.

```
{
  "errors": [
    {
      "message": "invalid type for variable: 'first'",
      "locations": [],
      "path": null,
      "extensions": {
        "type": "ValidationInvalidTypeVariable",
        "name": "first"
      }
    }
  ]
}
```

and changing the status code depending on that would require a SupergraphService plugin.

**Comment by o0Ignition0o** [comment] 2022-08-20 09:03
After a bit of thought, I think it should be a 400 since the variables fail to validate, and we already return a 400 if the query fails to validate. I'll prepare a PR and discuss this with the team on monday! :)

**Closed** 2022-08-22 08:24 UTC
Labels: raised by user

**Comment by xsoufiane** [comment] 2022-08-22 17:55
super thank you @o0Ignition0o

**Comment by xsoufiane** [comment] 2022-08-25 12:06
yes @o0Ignition0o and @Geal thank you 🙏  the issue was fixed
