### ISSUE TITLE
Escaped quotes in query yields "parsing error: ERROR@138:138 \"expected R_PAREN, got EOF" from v1.23

### ISSUE THREAD

**Issue by Bryji** [apollographql/router#3541] opened 2023-08-04 19:54 UTC
**Describe the bug**
Starting with router v1.23, using escaped quotes in a query (e.g. `reviewsForAuthor(authorID: "\"1\"")`) returns a parsing error

**To Reproduce**
1. Install Apollo router v1.23 or later
2. Fetch the starstuff demo project: curl -L https://supergraph.demo.starstuff.dev/ > starstuff.graphql
3. Execute a query with escaped quotes like:
```
query ExampleQuery {
  topProducts {
    reviewsForAuthor(authorID: "\"1\"") {
     body
    }
  }
}
```
4. An error is returned by the router (` error: ERROR`)

**Expected behavior**
Query should execute successfully as it has in the past. e.g.:
```
{
  "data": {
    "topProducts": [
      {
        "reviewsForAuthor": []
      },
      {
        "reviewsForAuthor": []
      },
      {
        "reviewsForAuthor": []
      }
    ]
  }
}
```

**Output**
```
{
  "data": {},
  "errors": [
    {
      "message": "parsing error: ERROR@104:104 \"expected R_PAREN, got EOF\" EOF\nERROR@104:104 \"expected R_CURLY, got EOF\" EOF\nERROR@104:104 \"expected R_CURLY, got EOF\" EOF",
      "extensions": {
        "code": "PARSING_ERROR"
      }
    }
  ]
}
```

**Desktop (please complete the following information):**
 - OS: MacOS, Linux
 - Version 1.23 onwards. Works in v1.22 an below.

**Additional context**
Using variables does work for this scenario.

**Comment by Geal** [comment] 2023-08-07 07:44
thank you for the report, we're looking into it

**Comment by SimonSapin** [comment] 2023-08-07 13:40
This involves both https://github.com/apollographql/apollo-rs/issues/611 and https://github.com/apollographql/apollo-rs/issues/612. (The latter because internally the Router serialize and reparses a modification of the query. We’re also working on avoiding the need for that.)

After fixing these apollo-rs bugs we’ll update the versions used in the Router.

**Comment by SimonSapin** [comment] 2023-11-03 11:19
This was fixed, most likely by https://github.com/apollographql/router/pull/4038 which will be part of Apollo Router 1.34. https://github.com/apollographql/router/pull/4135 adds a non-regression test.

**Closed** 2023-11-06 14:43 UTC
Labels: raised by user
